version: "3"
services:
  client:
    image: "wahlbergf100/multi-client"
    mem_limit: 128m
    hostname: client
    environment:
      - WDS_SOCKET_PORT=0
      - CI=true
  server:
    image: "wahlbergf100/multi-server"
    mem_limit: 256m
    hostname: api
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://wahlbergf100:kyhxEk0ZIUQnkEfO@blueprint-simplified.1qbxto9.mongodb.net/?retryWrites=true&w=majority&appName=blueprint-simplified
      - JWT_SECRET=32y4berufdsuyeew*734wr

  nginx:
    image: "wahlbergf100/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "3050:80"